FROM jenkins/inbound-agent:latest

USER root

RUN apt-get update && apt-get install -y maven docker.io curl && \
    curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins
            
